version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    working_dir: "/src"
    volumes:
      - ./src:/src
      - node_modules_volume:/src/node_modules
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: >
      /bin/sh -c "npm install && yarn dev"
volumes:
  node_modules_volume:
